name: CI/CD Pipeline

env:
  PYTHON_DIR: ci_cd_training/src

on:
  pull_request:
    branches: 
      - '**'
  push:
    branches:
      - '**'

jobs:

  # First job: Secret/Variables fetching

  # Second job: Python check

  python-quality-and-testing:
    name: "FastAPI code quality assessment and testing"

    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Requirements installment
        run: |
          cd ci_cd_training/src
          pip install -r requirements.txt
          pip install flake8
          pip install bandit
          pip install complexipy

      - name: Flake8 assessment
        id: flake8
        run: |
          echo "::group::Flake8 Linting for Python Source"
          flake8 ${{ env.PYTHON_DIR }}/
          echo "::endgroup:: # End Flake8 Linting"

      - name: Bandit SAST assessment
        id: bandit
        run: |
          echo "::group::Bandit Security Scan for Python Source"
          if [ -f "${{ env.PYTHON_DIR }}/.bandit" ]; then
            bandit -r ${{ env.PYTHON_DIR }}/ -ll --ini ${{ env.PYTHON_DIR }}/.bandit
          else
            bandit -r ${{ env.PYTHON_DIR }}/ -ll --skip B104
          fi
          echo "::endgroup:: # End Bandit Security Scan"

      - name: Cognitive Complexity assessment
        uses: rohaquinlop/complexipy-action@v3
        with:
            paths: './ci_cd_training/src/main.py'
            output_json: true
  

  # Third job: Terraform Plan/Apply - ONLY runs if Python checks pass
  terraform-deploy:
    name: "Terraform Deploy - ${{ github.base_ref || github.ref_name }}"
    needs: python-quality-and-testing
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Auth in GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

  # Fourth job: Cloud Function Healthcheck - ONLY runs if Terraform deploy passed