name: CI/CD Pipeline

on:
  pull_request:
    branches: 
      - '**'
  push:
    branches:
      - '**'

jobs:
  terraform-deploy:
    name: "Terraform Deploy - ${{ github.base_ref || github.ref_name }}"

    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Auth in GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}